server:
  port: "8080"
  host: "127.0.0.1"
  readTimeout: 5
  writeTimeout: 10
service:
  storage: "/data/"
routes:
  index:
    name: "index"
    route: "/"
    about: "this method for tell you about all methods"
  save:
    name: "save"
    route: "/api/{username}"
    about: "this method file saved by users"

