server:
  port: ":8080"
  readTimeout: 5
  writeTimeout: 10
service:
  storage: "/data/"
routes:
  index:
    name: "index"
    route: "/"
  save:
    name: "save"
    route: "/api/{username}"
    about: "this method file saved by users"

